const API='/api/pocket';
let dashboard=null,selectedDistrict='전체',searchText='',backPage='home',boundaryData=null,renewalStats=null,trustedSources=null,detailMap=null,onbidCache={};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmt=n=>n==null||n===''?'미확인':Number(n).toLocaleString('ko-KR');
const typeLabels={land:'토지',rowhouse:'연립다세대',detached:'단독다가구',apartment:'아파트'};
async function getJSON(action,params={}){const u=new URL(API,location.origin);u.searchParams.set('action',action);for(const[k,v]of Object.entries(params))u.searchParams.set(k,v);const r=await fetch(u,{cache:'no-store'}),t=await r.text();let j;try{j=JSON.parse(t)}catch{throw new Error('응답 형식 오류')};if(!r.ok)throw new Error(j.error||`HTTP ${r.status}`);return j}
async function loadStatic(){const urls=['/data/project_boundaries.geojson','/data/seoul_renewal_summary.json','/data/trusted_sources.json'];const r=await Promise.allSettled(urls.map(u=>fetch(u,{cache:'no-store'}).then(x=>x.json())));if(r[0].status==='fulfilled')boundaryData=r[0].value;if(r[1].status==='fulfilled')renewalStats=r[1].value;if(r[2].status==='fulfilled')trustedSources=r[2].value}
function boundaryFor(id){return boundaryData?.features?.find(f=>f.properties?.projectId===id)||null}
function showPage(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.getElementById(id)?.classList.add('active');document.querySelectorAll('.bottomnav button').forEach(b=>b.classList.toggle('on',b.dataset.page===id));scrollTo(0,0);if(id==='statusPage')loadStatus();if(id==='onbidPage')renderOnbidChooser();if(id==='dataPage')renderSources()}
document.querySelectorAll('.bottomnav button').forEach(b=>b.onclick=()=>showPage(b.dataset.page));
function grade(p){const m=p.market||{},cnt=Number(m.count||0),stage=String(p.stage||'');let s=45;if(stage.includes('정비구역'))s+=25;else if(stage.includes('정비계획'))s+=20;else if(stage.includes('후보지'))s+=15;s+=Math.min(15,cnt/2);if(p.areaSqm)s+=5;if(p.units)s+=5;if(p.rightsDate)s+=5;s=Math.round(Math.min(100,s));return{...p,_score:s,_grade:s>=80?'A':s>=65?'B':s>=50?'C':'D'}}
function typeSummary(p){const b=p.market?.byType||{};return Object.entries(typeLabels).map(([k,l])=>({k,l,count:Number(b[k]?.count||0),median:b[k]?.medianPricePerPyeongManwon||null,latest:b[k]?.latestDealDate||null}))}
function renderDashboard(d){dashboard={...d,projects:(d.projects||[]).map(grade)};document.getElementById('updated').textContent=`마지막 데이터: ${d.generatedAt||'미확인'}`;buildDistricts();applyFilter();renderMarket();renderNew()}
function buildDistricts(){const ds=['전체',...new Set((dashboard?.projects||[]).map(p=>p.district).filter(Boolean))];ds.sort((a,b)=>a==='전체'?-1:b==='전체'?1:a.localeCompare(b,'ko'));document.getElementById('districtFilters').innerHTML=ds.map(d=>`<button class="districtchip ${d===selectedDistrict?'on':''}" data-d="${esc(d)}">${esc(d)}</button>`).join('');document.querySelectorAll('.districtchip').forEach(b=>b.onclick=()=>{selectedDistrict=b.dataset.d;buildDistricts();applyFilter()})}
function applyFilter(){const q=searchText.trim().toLowerCase(),all=dashboard?.projects||[];const ps=all.filter(p=>(selectedDistrict==='전체'||p.district===selectedDistrict)&&(!q||[p.name,p.district,p.dong,p.stage].join(' ').toLowerCase().includes(q)));document.getElementById('count').textContent=ps.length===all.length?`${all.length}개`:`${ps.length}/${all.length}개`;document.getElementById('cards').innerHTML=ps.map(cardHTML).join('')||'<div class="empty">조건에 맞는 사업지가 없습니다.</div>'}
function cardHTML(p){return `<article class="card"><div class="area">${esc(p.district)} · ${esc(p.dong)}</div><div class="name">${esc(p.name)}</div><span class="stage">${esc(p.stage||'미확인')}</span><div class="facts"><div class="fact"><span>사업지 면적</span><b>${p.areaSqm?fmt(p.areaSqm)+'㎡':'미확인'}</b></div><div class="fact"><span>계획 세대수</span><b>${p.units?fmt(p.units)+'세대':'미확인'}</b></div><div class="fact"><span>권리산정기준일</span><b>${esc(p.rightsDate||'미확인')}</b></div><div class="fact"><span>참고 실거래</span><b>${fmt(p.market?.count||0)}건</b></div></div><div class="gradebox"><span class="grade ${p._grade}">${p._grade}</span><div class="why"><b>참고 가성비 ${p._score}점</b><br>사업단계·거래량·데이터 완성도 참고점수</div></div><div class="typechips">${typeSummary(p).map(t=>`<span class="typechip">${t.l} ${t.count}건</span>`).join('')}<span class="typechip ${boundaryFor(p.id)?'boundary-ok':'boundary-wait'}">${boundaryFor(p.id)?'✓ 구역경계 확보':'구역경계 대기'}</span></div><div class="actions"><a target="_blank" href="${p.maps?.naver||'#'}">네이버 지도</a><a target="_blank" href="${p.maps?.kakao||'#'}">카카오 지도</a><a target="_blank" href="${p.sourceUrl||'#'}">공식 출처</a></div><button class="detailbtn" onclick="openDetail('${p.id}')">사업지 상세 보기</button></article>`}
function renderMarket(){const ps=dashboard?.projects||[];document.getElementById('marketStamp').textContent=dashboard?.generatedAt||'';document.getElementById('marketList').innerHTML=ps.map(p=>`<article class="card"><div class="area">${esc(p.district)} · ${esc(p.dong)}</div><div class="name">${esc(p.name)}</div><div class="typechips">${typeSummary(p).map(t=>`<span class="typechip">${t.l} ${t.count}건</span>`).join('')}</div><button class="detailbtn" onclick="openDetail('${p.id}')">실거래 불러오기</button></article>`).join('')}
function renderNew(){const ps=[...(dashboard?.projects||[])].sort((a,b)=>String(b.selectedDate||'').localeCompare(String(a.selectedDate||'')));document.getElementById('newList').innerHTML=ps.map(cardHTML).join('')}
async function openDetail(id){backPage=document.querySelector('.page.active')?.id||'home';let p=dashboard?.projects?.find(x=>x.id===id);if(!p)return;showPage('detail');document.getElementById('detailTitle').textContent=p.name;document.getElementById('detailSub').textContent='실거래 불러오는 중…';document.getElementById('detailMain').innerHTML='<section class="section"><div class="card"><div class="loading">국토교통부 실거래 조회 중…</div></div></section>';try{const d=await getJSON('project',{id});p=grade(d.project);const i=dashboard.projects.findIndex(x=>x.id===id);if(i>=0)dashboard.projects[i]=p;renderDetail(p)}catch(e){document.getElementById('detailMain').innerHTML=`<section class="section"><div class="notice error"><b>실거래 조회 오류</b><br>${esc(e.message)}</div></section>`}}
function goBackFromDetail(){showPage(backPage||'home')}
function renderDetail(p){const m=p.market||{},bd=boundaryFor(p.id),deals=m.recentDeals||[];document.getElementById('detailTitle').textContent=p.name;document.getElementById('detailSub').textContent=`${p.district} ${p.dong} · ${p.stage||''}`;document.getElementById('detailMain').innerHTML=`<section class="section"><div class="section-head"><h2>사업 개요</h2><small>${p.selectedDate||''}</small></div><div class="card"><div class="facts"><div class="fact"><span>면적</span><b>${p.areaSqm?fmt(p.areaSqm)+'㎡':'미확인'}</b></div><div class="fact"><span>세대수</span><b>${p.units?fmt(p.units)+'세대':'미확인'}</b></div><div class="fact"><span>단계</span><b>${esc(p.stage||'미확인')}</b></div><div class="fact"><span>권리산정기준일</span><b>${esc(p.rightsDate||'미확인')}</b></div></div></div></section><section class="section"><div class="section-head"><h2>실거래</h2><small>법정동 참고</small></div><div class="card"><div class="data-status"><div class="status"><span>거래 건수</span><b>${fmt(m.count||0)}건</b></div><div class="status"><span>최근 거래일</span><b>${esc(m.latestDealDate||'없음')}</b></div><div class="status"><span>평당가 중앙값</span><b>${m.statistics?.medianPricePerPyeongManwon?fmt(m.statistics.medianPricePerPyeongManwon)+'만원':'미확인'}</b></div><div class="status"><span>API 오류</span><b>${(m.apiErrors||[]).length}건</b></div></div><div class="typechips">${typeSummary(p).map(t=>`<span class="typechip">${t.l} ${t.count}건${t.median?' · '+fmt(t.median)+'만/평':''}</span>`).join('')}</div></div></section><section class="section"><div class="section-head"><h2>사업구역 경계</h2><small>${bd?'Polygon 확보':'대기'}</small></div><div class="card">${bd?`<div id="boundaryMap" class="mapbox"></div><div class="notice" style="margin-top:10px;box-shadow:none">서울시 공간정보는 참고자료이며 법적 효력은 없습니다.</div>`:'<div class="empty">현재 공간정보에서 동일 사업지 Polygon이 확인되지 않았습니다.</div>'}</div></section><section class="section"><div class="section-head"><h2>최근 실거래</h2><small>최대 20건</small></div><div class="card">${deals.length?deals.map(x=>`<div class="trade"><div class="meta"><span>${esc(x.typeLabel)}</span><span>${esc(x.dealDate)}</span></div><b>${esc(x.umdNm||'')} ${esc(x.jibun||x.buildingName||'')}</b><div class="row"><span>${fmt(x.amountManwon)}만원 · ${fmt(x.areaSqm)}㎡</span><span>${x.pricePerPyeongManwon?fmt(x.pricePerPyeongManwon)+'만원/평':'-'}</span></div></div>`).join(''):'<div class="empty">최근 거래가 없습니다.</div>'}</div></section>`;if(bd&&window.L)setTimeout(()=>{if(detailMap)detailMap.remove();const el=document.getElementById('boundaryMap');if(!el)return;detailMap=L.map(el);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(detailMap);const layer=L.geoJSON(bd,{style:{weight:3,fillOpacity:.15}}).addTo(detailMap);detailMap.fitBounds(layer.getBounds(),{padding:[18,18]})},80)}
function renderOnbidChooser(){const box=document.getElementById('onbidProjectList'),q=(document.getElementById('onbidSearch')?.value||'').toLowerCase();const ps=(dashboard?.projects||[]).filter(p=>!q||[p.name,p.district,p.dong].join(' ').toLowerCase().includes(q));box.innerHTML=ps.map(p=>`<button class="card onbidpick" onclick="loadOnbidProject('${p.id}')"><div class="area">${esc(p.district)} · ${esc(p.dong)}</div><div class="name" style="font-size:14px">${esc(p.name)}</div><div class="meta"><span>선택해서 공매 조회</span><span>›</span></div></button>`).join('')}
async function loadOnbidProject(id){const p=dashboard?.projects?.find(x=>x.id===id);document.getElementById('onbidStamp').textContent=`${p?.name||''} 조회 중…`;document.getElementById('onbidList').innerHTML='<div class="loading">온비드 조회 중…</div>';try{const d=onbidCache[id]||await getJSON('onbid',{id});onbidCache[id]=d;const items=d.items||[];document.getElementById('onbidStamp').textContent=`${d.project?.name||''} · ${items.length}건`;document.getElementById('onbidList').innerHTML=items.length?items.map(x=>`<article class="card"><div class="area">${esc(x.address||'')}</div><div class="name" style="font-size:15px">${esc(x.name||'온비드 부동산 공매')}</div><div class="facts"><div class="fact"><span>감정가</span><b>${x.appraisalAmount?fmt(Math.round(x.appraisalAmount/10000))+'만원':'목록 API 미제공'}</b></div><div class="fact"><span>최저입찰가</span><b>${x.minimumBidAmount?fmt(Math.round(x.minimumBidAmount/10000))+'만원':'목록 API 미제공'}</b></div><div class="fact"><span>할인율</span><b>${x.discountRate!=null?x.discountRate+'%':'계산 불가'}</b></div><div class="fact"><span>입찰 마감</span><b>${esc(x.bidEnd||'미제공')}</b></div></div><div class="actions"><a target="_blank" href="https://www.onbid.co.kr/">온비드 공식</a><a target="_blank" href="https://map.naver.com/p/search/${encodeURIComponent(x.address||'')}">지도</a><button class="btn" onclick="openDetail('${id}')">사업지 비교</button></div></article>`).join(''):`<div class="card"><div class="empty">${esc(d.project?.district||'')} ${esc(d.project?.dong||'')}에서 현재 조회된 공매가 없습니다.</div></div>`}catch(e){document.getElementById('onbidList').innerHTML=`<div class="notice error"><b>온비드 조회 오류</b><br>${esc(e.message)}</div>`}}
async function loadStatus(){try{const d=await getJSON('status');document.getElementById('statusStamp').textContent=d.generatedAt||'';const m=d.molit||{},box=(n,v,ok)=>`<div class="status"><span>${n}</span><b class="${ok?'ready':'pending'}">${esc(v)}</b></div>`;document.getElementById('statusBox').innerHTML=[box('백엔드',d.backend||'미확인',d.backend==='Vercel'),box('Apps Script',d.appsScript===false?'사용 안 함':'사용 중',d.appsScript===false),box('서비스키',m.serviceKeySaved?'저장됨':'없음',!!m.serviceKeySaved),box('토지',m.land||'미확인',!!m.serviceKeySaved),box('연립다세대',m.rowhouse||'미확인',!!m.serviceKeySaved),box('단독다가구',m.detached||'미확인',!!m.serviceKeySaved),box('아파트',m.apartment||'미확인',!!m.serviceKeySaved),box('OnBid',d.onbid?.status||'미확인',d.onbid?.status==='연결')].join('')}catch(e){document.getElementById('statusBox').innerHTML=`<div class="notice error">상태 조회 오류: ${esc(e.message)}</div>`}}
function renderSources(){const list=document.getElementById('sourceList');if(!trustedSources){list.innerHTML='<div class="empty">자료원 정보를 불러오지 못했습니다.</div>';return}document.getElementById('sourceStamp').textContent=trustedSources.generatedAt||'';list.innerHTML=(trustedSources.sources||[]).map(s=>`<article class="card source-card"><div class="source-top"><span class="trust">${esc(s.trust)}</span><b>${esc(s.status)}</b></div><h3>${esc(s.name)}</h3><p><b>용도:</b> ${esc(s.use)}<br><b>방식:</b> ${esc(s.method)}<br>${esc(s.note)}</p></article>`).join('');if(renewalStats){document.getElementById('renewalCount').textContent=`${renewalStats.count||0}개 구역`;const a=Object.entries(renewalStats.stageSummary||{}).sort((x,y)=>y[1]-x[1]).slice(0,6);document.getElementById('renewalSummary').innerHTML=`<div class="typechips">${a.map(x=>`<span class="typechip">${esc(x[0])} ${x[1]}</span>`).join('')}</div>`}}
async function load(){await loadStatic();try{renderDashboard(await getJSON('dashboard'))}catch(e){document.getElementById('cards').innerHTML=`<div class="notice error"><b>데이터 연결 오류</b><br>${esc(e.message)}</div>`}}
document.getElementById('refreshBtn').onclick=async()=>{const b=document.getElementById('refreshBtn');b.disabled=true;b.textContent='새로고침 중…';try{renderDashboard(await getJSON('refresh'))}catch(e){alert(e.message)}finally{b.disabled=false;b.textContent='새로고침'}};
const s=document.getElementById('projectSearch');s?.addEventListener('input',e=>{searchText=e.target.value||'';applyFilter()});document.getElementById('clearSearch')?.addEventListener('click',()=>{searchText='';s.value='';applyFilter()});document.getElementById('onbidSearch')?.addEventListener('input',renderOnbidChooser);document.getElementById('clearOnbidSearch')?.addEventListener('click',()=>{document.getElementById('onbidSearch').value='';renderOnbidChooser()});
load();
