// Official data enrichment: OnBid full dataset + detail + Seoul official sources. No observers/polling.
(() => {
  'use strict';
  const e=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const money=n=>n!=null&&Number.isFinite(Number(n))?Number(n).toLocaleString('ko-KR')+'원':'미확인';
  let onbidAll=null,onbidAllPromise=null;
  async function fetchJson(url){const r=await fetch(url,{cache:'default'}),text=await r.text();let d;try{d=JSON.parse(text)}catch{throw new Error('서버 응답 형식 오류')}if(!r.ok||d.ok===false)throw new Error(d.error||('HTTP '+r.status));return d}
  function projectById(id){try{return (dashboard?.projects||[]).find(x=>x.id===id)||null}catch{return null}}
  function dedupe(rows){const seen=new Set(),out=[];for(const x of rows||[]){const k=[x.cltrMngNo,x.pbctCdtnNo,x.name,x.address].join('|');if(seen.has(k))continue;seen.add(k);out.push(x)}return out}
  async function loadAllOnbid(){
    if(onbidAll)return onbidAll;if(onbidAllPromise)return onbidAllPromise;
    onbidAllPromise=(async()=>{
      const manifest=await fetchJson('/api/onbid?manifest=1');
      const rows=[];const errors=[...(manifest.apiErrors||[])];
      const jobs=[];
      for(const scan of (manifest.scans||[])){
        rows.push(...(scan.firstItems||[]));
        for(let page=2;page<=Number(scan.pages||1);page++)jobs.push({code:scan.code,page});
      }
      const BATCH=10;
      for(let i=0;i<jobs.length;i+=BATCH){
        const batch=jobs.slice(i,i+BATCH);
        const results=await Promise.allSettled(batch.map(j=>fetchJson('/api/onbid?code='+encodeURIComponent(j.code)+'&page='+j.page)));
        results.forEach((r,idx)=>{if(r.status==='fulfilled')rows.push(...(r.value.items||[]));else errors.push({propertyCode:batch[idx].code,page:batch[idx].page,message:String(r.reason?.message||r.reason)})});
      }
      const data={ok:true,version:manifest.version||'9.0.0',generatedAt:manifest.generatedAt,items:dedupe(rows),apiErrors:errors,scanCoverage:{complete:errors.length===0,rowsPerPage:manifest.rowsPerPage,scans:(manifest.scans||[]).map(x=>({propertyCode:x.code,totalCount:x.totalCount,pagesScanned:x.pages,complete:true}))}};
      onbidAll=data;return data;
    })().finally(()=>onbidAllPromise=null);
    return onbidAllPromise;
  }
  function localItems(d,p){const rows=d.items||[];return rows.filter(x=>{const blob=[x.address,x.sido,x.district,x.dong,x.name].join(' ');return blob.includes(p.district)&&blob.includes(p.dong)}).sort((a,b)=>String(a.bidEnd||'9999').localeCompare(String(b.bidEnd||'9999')))}
  function appendOfficialBox(id,d,changed){const main=document.getElementById('detailMain');if(!main)return;main.querySelector('.official-enrich-section')?.remove();const src=(d.sources||[]).filter(x=>x.ok).map(x=>x.type).join(' · ')||'서울시 공식자료',vals=d.official||{},rows=[['면적',vals.areaSqm?Number(vals.areaSqm).toLocaleString('ko-KR')+'㎡':'추가 확인값 없음'],['계획 세대수',vals.units?Number(vals.units).toLocaleString('ko-KR')+'세대':'추가 확인값 없음'],['권리산정기준일',vals.rightsDate||'추가 확인값 없음'],['정비구역 지정일',vals.designationDate||'추가 확인값 없음']];const sec=document.createElement('section');sec.className='section official-enrich-section';sec.innerHTML=`<div class="section-head"><h2>서울시 공식자료 보강</h2><small>${changed?'미확인 값 반영':'확인 완료'}</small></div><div class="card"><div class="facts">${rows.map(([a,b])=>`<div class="fact"><span>${e(a)}</span><b>${e(b)}</b></div>`).join('')}</div><div class="notice" style="margin-top:10px;box-shadow:none"><b>출처</b> ${e(src)}<br>공식 페이지에서 항목명이 명확히 확인되는 값만 사용하며 추정값은 넣지 않습니다.</div></div>`;main.appendChild(sec)}
  const oldOpen=window.openDetail;if(typeof oldOpen==='function')window.openDetail=async function(id){await oldOpen(id);try{const d=await fetchJson('/api/seoul-official?id='+encodeURIComponent(id)),vals=d.official||{};let p=projectById(id),changed=false;if(p){for(const k of ['areaSqm','units','rightsDate','designationDate'])if((p[k]==null||p[k]==='')&&vals[k]!=null&&vals[k]!==''){p[k]=vals[k];changed=true}if(changed){try{renderDetail(p);applyFilter();renderNew()}catch{}}}appendOfficialBox(id,d,changed)}catch{}};
  function setCardValue(card,selector,value){const el=card?.querySelector(selector);if(el)el.textContent=value}
  function setDetailExtra(card,x){const box=card?.querySelector('.onbid-detail-box');if(!box)return;box.innerHTML=`<div class="onbid-detail-extra"><span>토지면적<b>${x.landSqm?e(x.landSqm+'㎡'):'미제공'}</b></span><span>건물면적<b>${x.buildingSqm?e(x.buildingSqm+'㎡'):'미제공'}</b></span></div>`}
  window.ensureOnbidDetail=async function(card){if(!card||card.dataset.detailState==='loading'||card.dataset.detailState==='loaded')return;const cltr=card.dataset.cltr||'',pbct=card.dataset.pbct||'';if(!cltr){card.dataset.detailState='error';return}card.dataset.detailState='loading';['.onbid-value-appraisal','.onbid-value-minimum','.onbid-value-discount','.onbid-value-end'].forEach(s=>setCardValue(card,s,'조회 중…'));try{const d=await fetchJson('/api/onbid-detail?cltrMngNo='+encodeURIComponent(cltr)+(pbct?'&pbctCdtnNo='+encodeURIComponent(pbct):'')),x=d.item||{};setCardValue(card,'.onbid-value-appraisal',x.appraisalAmount!=null?money(x.appraisalAmount):'미확인');setCardValue(card,'.onbid-value-minimum',x.minimumBidAmount!=null?money(x.minimumBidAmount):'미확인');setCardValue(card,'.onbid-value-discount',x.discountRate!=null?e(x.discountRate+'%'):'계산 불가');setCardValue(card,'.onbid-value-end',e(x.bidEnd||'미확인'));setDetailExtra(card,x);card.dataset.detailState='loaded'}catch(err){card.dataset.detailState='error'}};
  function onbidNotice(d){const notes=[];if((d.apiErrors||[]).length)notes.push(`재산유형/페이지 ${(d.apiErrors||[]).length}개 조회 실패`);if(d.scanCoverage&&d.scanCoverage.complete===false)notes.push('전체 데이터 일부 페이지를 수집하지 못했습니다.');return notes.length?`<div class="notice" style="margin-bottom:10px"><b>온비드 조회 상태</b><br>${notes.map(e).join('<br>')}</div>`:''}
  window.loadOnbidProject=async function(id){const p=projectById(id),stamp=document.getElementById('onbidStamp'),list=document.getElementById('onbidList');if(stamp)stamp.textContent=(p?.name||'')+' 전체 데이터 확인 중…';if(list)list.innerHTML='<div class="loading">온비드 전국 전체 페이지 자료를 불러온 뒤 지역을 확인합니다. 최초 조회는 시간이 걸릴 수 있습니다.</div>';try{const d=await loadAllOnbid(),items=p?localItems(d,p):[];if(stamp)stamp.textContent=(p?.name||'')+' · '+items.length+'건';if(!list)return;const warn=onbidNotice(d),cards=items.length?items.map(x=>{const cltr=e(x.cltrMngNo||''),pbct=e(x.pbctCdtnNo||'');return `<article class="card" data-cltr="${cltr}" data-pbct="${pbct}" data-detail-state=""><div class="area">${e(x.address||'')}</div><div class="name" style="font-size:15px">${e(x.name||'온비드 부동산 공매')}</div><div class="facts"><div class="fact"><span>감정가</span><b class="onbid-value-appraisal">${x.appraisalAmount!=null?money(x.appraisalAmount):'미확인'}</b></div><div class="fact"><span>최저입찰가</span><b class="onbid-value-minimum">${x.minimumBidAmount!=null?money(x.minimumBidAmount):'미확인'}</b></div><div class="fact"><span>할인율</span><b class="onbid-value-discount">${x.discountRate!=null?e(x.discountRate+'%'):'미확인'}</b></div><div class="fact"><span>입찰 마감</span><b class="onbid-value-end">${e(x.bidEnd||'미확인')}</b></div></div><div class="onbid-detail-box">${(x.landSqm||x.buildingSqm)?`<div class="onbid-detail-extra"><span>토지면적<b>${x.landSqm?e(x.landSqm+'㎡'):'미제공'}</b></span><span>건물면적<b>${x.buildingSqm?e(x.buildingSqm+'㎡'):'미제공'}</b></span></div>`:''}</div><div class="actions"><a target="_blank" href="https://www.onbid.co.kr/">온비드 공식</a><a target="_blank" href="https://map.naver.com/p/search/${encodeURIComponent(x.address||'')}">지도</a></div></article>`}).join(''):`<div class="card"><div class="empty"><b>전체 조회 자료에서 일치 공매 없음</b><br>${e(p?.district||'')} ${e(p?.dong||'')} 기준입니다.${d.scanCoverage?.complete===false?'<br>일부 페이지 수집 실패로 0건 확정값은 아닙니다.':''}</div></div>`;list.innerHTML=warn+cards}catch(err){if(stamp)stamp.textContent='조회 오류';if(list)list.innerHTML='<div class="notice error"><b>온비드 조회 오류</b><br>'+e(err.message)+'</div>'}};
  const style=document.createElement('style');style.textContent=`.onbid-detail-extra{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:10px 0}.onbid-detail-extra span{display:block;background:#f7f7f7;border:1px solid #e7e7e7;border-radius:10px;padding:9px;font-size:9px;color:#777}.onbid-detail-extra b{display:block;margin-top:2px;font-size:11px;color:#222}`;document.head.appendChild(style);
})();