import { XMLParser } from 'fast-xml-parser';
import projectsPayload from '../data/projects.json' with { type: 'json' };

const PROJECTS=projectsPayload.projects||[];
const BASE='https://apis.data.go.kr/B010003/OnbidRlstListSrvc2/getRlstCltrList2';
const CODES=['0007','0010','0005','0002','0003'];
const ROWS=200,MAX_PAGES=30,BATCH=5;
const xml=new XMLParser({ignoreAttributes:false,trimValues:true});
function key(){const raw=(process.env.DATA_GO_KR_SERVICE_KEY||'').trim();if(!raw)throw new Error('DATA_GO_KR_SERVICE_KEY가 없습니다.');try{return decodeURIComponent(raw)}catch{return raw}}
function arr(v){return v==null?[]:Array.isArray(v)?v:[v]}
function num(v){const s=String(v??'').trim();if(!s)return null;const c=s.replace(/,/g,'').replace(/[^\d.-]/g,'');if(!c||c==='-'||c==='.')return null;const n=Number(c);return Number.isFinite(n)?n:null}
function pickCI(o,ks){const m={};for(const[k,v]of Object.entries(o||{}))m[k.toLowerCase()]=v;for(const k of ks){const v=m[k.toLowerCase()];if(v!=null&&String(v).trim()!=='')return String(v).trim()}return''}
function numCI(o,k){return num(pickCI(o,k))}
function bodyOf(d){return d?.response?.body||d?.body||d}
function rowsOf(d){const b=bodyOf(d);return arr(b?.items?.item??b?.items??b?.item??b?.data??b?.result??b?.list??[])}
function totalOf(d){const b=bodyOf(d);return num(b?.totalCount??b?.totalCnt??b?.totCnt??b?.total??0)||0}
function parseBody(t,ct){t=String(t||'').trim();if(!t)return{};if((ct||'').includes('json')||t.startsWith('{')||t.startsWith('[')){try{return JSON.parse(t)}catch{}}if(t.startsWith('<'))return xml.parse(t);throw new Error('온비드 응답 형식을 해석하지 못했습니다.')}
function serviceError(d){const h=d?.response?.header||d?.header||d?.OpenAPI_ServiceResponse?.cmmMsgHeader;if(!h)return null;const c=String(h.resultCode??h.returnReasonCode??'').trim(),m=String(h.resultMsg??h.errMsg??h.returnAuthMsg??'').trim();if(h.errMsg||h.returnAuthMsg||(c&&!['0','00','000'].includes(c)))return new Error(`온비드 API ${c||'오류'}: ${m||'요청 실패'}`);return null}
async function page(code,pageNo){const u=new URL(BASE);for(const[k,v]of Object.entries({serviceKey:key(),pageNo:String(pageNo),numOfRows:String(ROWS),resultType:'json',prptDivCd:code,pvctTrgtYn:'N'}))u.searchParams.set(k,v);const c=new AbortController(),tm=setTimeout(()=>c.abort(),7000);try{const r=await fetch(u,{signal:c.signal,headers:{Accept:'application/json,application/xml,text/xml,*/*','User-Agent':'SeoulRedevelopmentPocket/8.2'}});const text=await r.text();if(!r.ok)throw new Error(`HTTP ${r.status}`);const d=parseBody(text,r.headers.get('content-type')||'');const er=serviceError(d);if(er)throw er;return{rows:rowsOf(d),total:totalOf(d)}}finally{clearTimeout(tm)}}
async function allForCode(code){const first=await page(code,1),total=first.total||first.rows.length,pages=Math.min(MAX_PAGES,Math.max(1,Math.ceil(total/ROWS)));let rows=[...first.rows];for(let start=2;start<=pages;start+=BATCH){const nums=Array.from({length:Math.min(BATCH,pages-start+1)},(_,i)=>start+i);const set=await Promise.allSettled(nums.map(n=>page(code,n)));for(const r of set)if(r.status==='fulfilled')rows.push(...r.value.rows)}return{code,rows,total,pagesScanned:pages,complete:pages*ROWS>=total}}
function normalize(x){const appraisal=numCI(x,['apslEvlAmt','cltrApslEvlAvgAmt','apslEvlAvgAmt']),minimum=numCI(x,['lowstBidPrc','minBidPrc','lowstBidAmt','frstBidPrc']);const sido=pickCI(x,['lctnSdnm','sdnm','SIDO_NM','CTPV_NM']),district=pickCI(x,['lctnSggnm','sggnm','SGG_NM']),dong=pickCI(x,['lctnEmdNm','emdNm','EMD_NM']);let address=pickCI(x,['sidoSgkEmd','sidoSggEmd','radr','zadr','lctnAddr','addr','address','LDNM_ADRS','ROAD_NM_ADDR']);if(!address)address=[sido,district,dong].filter(Boolean).join(' ');return{cltrMngNo:pickCI(x,['cltrMngNo']),pbctCdtnNo:pickCI(x,['pbctCdtnNo']),name:pickCI(x,['onbidCltrNm','cltrNm','goodsNm'])||'온비드 부동산 공매',address,sido,district,dong,appraisalAmount:appraisal,minimumBidAmount:minimum,discountRate:appraisal!=null&&appraisal>0&&minimum!=null?Math.round((1-minimum/appraisal)*1000)/10:null,landSqm:numCI(x,['landSqms','landSqm']),buildingSqm:numCI(x,['bldSqms','bldSqm']),bidEnd:pickCI(x,['pbctDdlnDt','pbctLastDdlnDt','bidEndDtm','PBCT_CLS_DTM'])}}
function match(x,p){const blob=[x.address,x.sido,x.district,x.dong,x.name].join(' ');return blob.includes(p.district)&&blob.includes(p.dong)}
export default async function handler(req,res){try{const settled=await Promise.allSettled(CODES.map(allForCode));let raw=[],scans=[],apiErrors=[];settled.forEach((r,i)=>{if(r.status==='fulfilled'){raw.push(...r.value.rows);scans.push({propertyCode:r.value.code,totalCount:r.value.total,pagesScanned:r.value.pagesScanned,complete:r.value.complete})}else apiErrors.push({propertyCode:CODES[i],message:String(r.reason?.message||r.reason)})});const seen=new Set(),all=[];for(const r of raw){const x=normalize(r),k=[x.cltrMngNo,x.pbctCdtnNo,x.name,x.address].join('|');if(seen.has(k))continue;seen.add(k);all.push(x)}const complete=apiErrors.length===0&&scans.every(s=>s.complete);res.setHeader('Cache-Control','public, s-maxage=21600, stale-while-revalidate=43200');if(String(req.query.all||'')==='1')return res.status(200).json({ok:true,version:'8.2.0',generatedAt:new Date().toISOString(),count:all.length,items:all,apiErrors,scanCoverage:{complete,rowsPerPage:ROWS,maxPagesPerPropertyCode:MAX_PAGES,scans}});const p=PROJECTS.find(x=>x.id===String(req.query.id||''));if(!p)return res.status(404).json({ok:false,error:'사업지를 찾을 수 없습니다.'});const items=all.filter(x=>match(x,p)).sort((a,b)=>String(a.bidEnd||'9999').localeCompare(String(b.bidEnd||'9999')));return res.status(200).json({ok:true,version:'8.2.0',generatedAt:new Date().toISOString(),project:{id:p.id,name:p.name,district:p.district,dong:p.dong},count:items.length,items,apiErrors,scanCoverage:{complete,rowsPerPage:ROWS,maxPagesPerPropertyCode:MAX_PAGES,scans},coverageNote:complete?'전체 페이지 범위를 확인했습니다.':'재산유형별 최대 30페이지까지 수집했습니다. 일부 유형은 더 많은 페이지가 있을 수 있습니다.'})}catch(e){res.setHeader('Cache-Control','no-store');return res.status(500).json({ok:false,error:String(e?.message||e),version:'8.2.0'})}}
